package com.sheen.adb.ui

enum class V01StringKey(val semanticKey: String) {
    MENU("menu.title"),
    HISTORY_DEVICES("menu.history"),
    SETTINGS("menu.settings"),
    ABOUT("menu.about"),
    LANGUAGE("settings.language"),
    LANGUAGE_CHINESE("settings.language.chinese"),
    LANGUAGE_ENGLISH("settings.language.english"),
    TOP_CONNECT("top.connect"),
    TOP_DISCONNECT("top.disconnect"),
    NAV_CONNECT("nav.connect"),
    NAV_FILES("nav.files"),
    NAV_APPS("nav.apps"),
    NAV_PROCESSES("nav.processes"),
    NAV_TERMINAL("nav.terminal"),
    NAV_LOGS("nav.logs"),
    CONNECTION_ENDPOINT_HINT("connection.endpoint.hint"),
    CONNECTION_ENDPOINT_CONTENT_DESCRIPTION("connection.endpoint.content_description"),
    CONNECTION_CONNECTING("connection.connecting"),
    CONNECTION_CONNECTED("connection.connected"),
    CONNECTION_DISCONNECTING("connection.disconnecting"),
    CONNECTION_DISCONNECTED("connection.disconnected"),
    PAIRING_SCAN("pairing.scan"),
    PAIRING_SCANNING("pairing.scanning"),
    PAIRING_QR("pairing.qr"),
    PAIRING_CODE("pairing.code"),
    PAIRING_LOCAL("pairing.local"),
    PAIRING_WAITING("pairing.waiting"),
    ERROR_INVALID_ENDPOINT("error.invalid_endpoint"),
    ERROR_CONNECTION_FAILED("error.connection_failed"),
    ERROR_TIMEOUT("error.timeout"),
    ERROR_CANCELLED("error.cancelled"),
    ERROR_DEVICE_DISCONNECTED("error.device_disconnected"),
    ERROR_UNSUPPORTED("error.unsupported"),
    ERROR_UNKNOWN("error.unknown"),
    EMPTY_DISCOVERY("empty.discovery"),
    EMPTY_HISTORY("empty.history"),
    EMPTY_OVERVIEW("empty.overview"),
    VALUE_UNKNOWN("value.unknown"),
    VALUE_UNAVAILABLE("value.unavailable"),
    ABOUT_SUPPORT("about.support"),
    ABOUT_OPEN_GITHUB("about.open_github"),
    QUICK_SCREENSHOT("quick.screenshot"),
    QUICK_RECORD("quick.record"),
    QUICK_REBOOT("quick.reboot"),
    QUICK_RECORDING("quick.recording"),
    QUICK_STOP("quick.stop"),
    QUICK_EXPORT("quick.export"),
    QUICK_EXPORT_CANCELLED("quick.export_cancelled"),
    QUICK_REBOOT_CONFIRM("quick.reboot_confirm"),
    QUICK_REBOOT_RISK("quick.reboot_risk"),
    QUICK_UNSUPPORTED("quick.unsupported"),
    QUICK_RESULT_UNKNOWN("quick.result_unknown"),
}

object V01Strings {
    private val catalogs: Map<UiLanguage, Map<V01StringKey, String>> = mapOf(
        UiLanguage.ZH_CN to mapOf(
            V01StringKey.CONNECTION_ENDPOINT_CONTENT_DESCRIPTION to "\u0041\u0044\u0042 \u8c03\u8bd5\u5730\u5740",
            V01StringKey.MENU to "菜单",
            V01StringKey.HISTORY_DEVICES to "历史设备",
            V01StringKey.SETTINGS to "设置",
            V01StringKey.ABOUT to "关于",
            V01StringKey.LANGUAGE to "语言",
            V01StringKey.LANGUAGE_CHINESE to "简体中文",
            V01StringKey.LANGUAGE_ENGLISH to "English",
            V01StringKey.TOP_CONNECT to "连接",
            V01StringKey.TOP_DISCONNECT to "断开连接",
            V01StringKey.NAV_CONNECT to "连接",
            V01StringKey.NAV_FILES to "文件",
            V01StringKey.NAV_APPS to "应用",
            V01StringKey.NAV_PROCESSES to "进程",
            V01StringKey.NAV_TERMINAL to "终端",
            V01StringKey.NAV_LOGS to "日志",
            V01StringKey.CONNECTION_ENDPOINT_HINT to "请输入 IP:端口",
            V01StringKey.CONNECTION_CONNECTING to "正在连接",
            V01StringKey.CONNECTION_CONNECTED to "已连接",
            V01StringKey.CONNECTION_DISCONNECTING to "正在断开",
            V01StringKey.CONNECTION_DISCONNECTED to "未连接",
            V01StringKey.PAIRING_SCAN to "扫描局域网设备",
            V01StringKey.PAIRING_SCANNING to "正在扫描",
            V01StringKey.PAIRING_QR to "扫描二维码连接",
            V01StringKey.PAIRING_CODE to "配对码配对",
            V01StringKey.PAIRING_LOCAL to "本机配对",
            V01StringKey.PAIRING_WAITING to "等待设备完成配对",
            V01StringKey.ERROR_INVALID_ENDPOINT to "请输入有效的 IP 和端口",
            V01StringKey.ERROR_CONNECTION_FAILED to "连接失败，请重试",
            V01StringKey.ERROR_TIMEOUT to "操作超时",
            V01StringKey.ERROR_CANCELLED to "操作已取消",
            V01StringKey.ERROR_DEVICE_DISCONNECTED to "设备已断开",
            V01StringKey.ERROR_UNSUPPORTED to "当前设备不支持此功能",
            V01StringKey.ERROR_UNKNOWN to "发生未知错误",
            V01StringKey.EMPTY_DISCOVERY to "未发现可用设备",
            V01StringKey.EMPTY_HISTORY to "暂无历史设备",
            V01StringKey.EMPTY_OVERVIEW to "设备未提供概览信息",
            V01StringKey.VALUE_UNKNOWN to "未知",
            V01StringKey.VALUE_UNAVAILABLE to "设备未提供",
            V01StringKey.ABOUT_SUPPORT to "制作不易，请帮忙到 GitHub 点个 Star。",
            V01StringKey.ABOUT_OPEN_GITHUB to "打开 GitHub",
            V01StringKey.QUICK_SCREENSHOT to "截屏",
            V01StringKey.QUICK_RECORD to "录屏",
            V01StringKey.QUICK_REBOOT to "重启",
            V01StringKey.QUICK_RECORDING to "正在录制",
            V01StringKey.QUICK_STOP to "停止",
            V01StringKey.QUICK_EXPORT to "选择导出位置",
            V01StringKey.QUICK_EXPORT_CANCELLED to "已取消导出",
            V01StringKey.QUICK_REBOOT_CONFIRM to "确认重启被控设备",
            V01StringKey.QUICK_REBOOT_RISK to "设备连接将中断，未保存的数据可能丢失，结果也可能无法确认。",
            V01StringKey.QUICK_UNSUPPORTED to "设备不支持此操作",
            V01StringKey.QUICK_RESULT_UNKNOWN to "操作结果未知",
        ),
        UiLanguage.EN_US to mapOf(
            V01StringKey.CONNECTION_ENDPOINT_CONTENT_DESCRIPTION to "ADB debug address",
            V01StringKey.MENU to "Menu",
            V01StringKey.HISTORY_DEVICES to "Connection history",
            V01StringKey.SETTINGS to "Settings",
            V01StringKey.ABOUT to "About",
            V01StringKey.LANGUAGE to "Language",
            V01StringKey.LANGUAGE_CHINESE to "Simplified Chinese",
            V01StringKey.LANGUAGE_ENGLISH to "English",
            V01StringKey.TOP_CONNECT to "Connect",
            V01StringKey.TOP_DISCONNECT to "Disconnect",
            V01StringKey.NAV_CONNECT to "Connect",
            V01StringKey.NAV_FILES to "Files",
            V01StringKey.NAV_APPS to "Apps",
            V01StringKey.NAV_PROCESSES to "Processes",
            V01StringKey.NAV_TERMINAL to "Terminal",
            V01StringKey.NAV_LOGS to "Logs",
            V01StringKey.CONNECTION_ENDPOINT_HINT to "Enter IP:port",
            V01StringKey.CONNECTION_CONNECTING to "Connecting",
            V01StringKey.CONNECTION_CONNECTED to "Connected",
            V01StringKey.CONNECTION_DISCONNECTING to "Disconnecting",
            V01StringKey.CONNECTION_DISCONNECTED to "Not connected",
            V01StringKey.PAIRING_SCAN to "Scan for devices",
            V01StringKey.PAIRING_SCANNING to "Scanning",
            V01StringKey.PAIRING_QR to "Connect with QR code",
            V01StringKey.PAIRING_CODE to "Pair with code",
            V01StringKey.PAIRING_LOCAL to "Pair this device",
            V01StringKey.PAIRING_WAITING to "Waiting for the device to pair",
            V01StringKey.ERROR_INVALID_ENDPOINT to "Enter a valid IP address and port",
            V01StringKey.ERROR_CONNECTION_FAILED to "Connection failed. Try again.",
            V01StringKey.ERROR_TIMEOUT to "Operation timed out",
            V01StringKey.ERROR_CANCELLED to "Operation cancelled",
            V01StringKey.ERROR_DEVICE_DISCONNECTED to "Device disconnected",
            V01StringKey.ERROR_UNSUPPORTED to "This device does not support this feature",
            V01StringKey.ERROR_UNKNOWN to "An unknown error occurred",
            V01StringKey.EMPTY_DISCOVERY to "No available devices found",
            V01StringKey.EMPTY_HISTORY to "No connection history",
            V01StringKey.EMPTY_OVERVIEW to "The device did not provide overview information",
            V01StringKey.VALUE_UNKNOWN to "Unknown",
            V01StringKey.VALUE_UNAVAILABLE to "Not provided by device",
            V01StringKey.ABOUT_SUPPORT to "This project takes time to make. Please give it a Star on GitHub.",
            V01StringKey.ABOUT_OPEN_GITHUB to "Open GitHub",
            V01StringKey.QUICK_SCREENSHOT to "Screenshot",
            V01StringKey.QUICK_RECORD to "Screen record",
            V01StringKey.QUICK_REBOOT to "Reboot",
            V01StringKey.QUICK_RECORDING to "Recording",
            V01StringKey.QUICK_STOP to "Stop",
            V01StringKey.QUICK_EXPORT to "Choose export location",
            V01StringKey.QUICK_EXPORT_CANCELLED to "Export cancelled",
            V01StringKey.QUICK_REBOOT_CONFIRM to "Reboot the controlled device?",
            V01StringKey.QUICK_REBOOT_RISK to "The connection will end, unsaved data may be lost, and the result may be unknown.",
            V01StringKey.QUICK_UNSUPPORTED to "This operation is not supported by the device",
            V01StringKey.QUICK_RESULT_UNKNOWN to "Operation result unknown",
        ),
    )

    fun text(language: UiLanguage, key: V01StringKey): String =
        catalogs[language]?.get(key)
            ?: catalogs.getValue(UiLanguage.ZH_CN)[key]
            ?: key.semanticKey

    fun text(language: UiLanguage, semanticKey: String): String =
        V01StringKey.entries.firstOrNull { it.semanticKey == semanticKey }
            ?.let { text(language, it) }
            ?: semanticKey
}
